### ISSUE TITLE
Link Error Exception trying to load the LWJGL Library

### ISSUE THREAD

**Issue by bms-1984** [Fox2Code/FoxLoaderExampleMod#1]
Happening anytime I try to run the client in my own mod, thought it was something I did, but I attempted to run on a fresh clone and got the same thing. The game window blue screens and it just hangs. There is no `liblwjgl.dylib` in `./run/natives`, but there is a `liblwjgl.jnilib`.

Server runs fine.

I run macOS if that matters, since I'm aware `.dylib` is an Apple equivalent to `.dll` on Windows or `.so` on *nix (though we have traditional shared objects on macOS also, lol.)

```
Exception in thread "Minecraft main thread" [16:58:19] [STDERR ] java.lang.UnsatisfiedLinkError: Can't load library: /Users/bms/FoxLoaderExampleMod/run/natives/liblwjgl.dylib
[16:58:19] [STDERR ] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
[16:58:19] [STDERR ] 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
[16:58:19] [STDERR ] 	at java.base/java.lang.System.load(System.java:1953)
[16:58:19] [STDERR ] 	at org.lwjgl.Sys$1.run(Sys.java:70)
[16:58:19] [STDERR ] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[16:58:19] [STDERR ] 	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
[16:58:19] [STDERR ] 	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
[16:58:19] [STDERR ] 	at org.lwjgl.Sys.<clinit>(Sys.java:112)
[16:58:19] [STDERR ] 	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
[16:58:19] [STDERR ] 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:257)
[16:58:19] [STDERR ] 	at net.minecraft.client.Minecraft.run(Minecraft.java:555)
[16:58:19] [STDERR ] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Fox2Code** [comment]
@bms-1984 is your Mac an ARM Mac? LWJGL 2 doesn't support MacOS ARM, please run the project under rosetta to run x86-64 version of java instead.

Also you reported the issue in the wrong place: <https://github.com/Fox2Code/FoxLoader>

Note: LWJGL 3 work fine with ARM MacOS, but upgrading the game form LWJGL 2 to LWJGL 3 is not that simple, and out of scope of the FoxLoader project.
